### ISSUE TITLE
Unsupported lookup 'net_overlaps' for CidrAddressField

### ISSUE THREAD

**Issue by oza4h07** [jimfunk/django-postgresql-netfields#106]
models.py:

`class LAN(models.Model):
   network_address = CidrAddressField()
    objects = NetManager()`

within shell_plus session:
`
>>> from ipaddress import IPv4Network
>>> LAN.objects.create(network_address=IPv4Network('192.168.2.0/24'))
>>> net2 = IPv4Network('192.168.2.64/26')
>>> LAN.objects.filter(network_address__net_overlaps=net2)
...
django.core.exceptions.FieldError: Unsupported lookup 'net_overlaps' for CidrAddressField or join on the field not permitted.
`
Django is 3.0.7 and django-netfields is 1.2.2.

Thoughts ?

**Comment by jimfunk** [comment]
I can't reproduce this using CidrTestModel from the test app:

    >>> CidrTestModel.objects.create(field=IPv4Network('192.168.2.0/24'))
    <CidrTestModel: CidrTestModel object (2)>
    >>> net2 = IPv4Network('192.168.2.64/26')
    >>> CidrTestModel.objects.filter(field__net_overlaps=IPv4Network('192.168.2.64/26'))
    <QuerySet [<CidrTestModel: CidrTestModel object (2)>]>

This is with Django 3.0.7 and the master branch.

Can you provide a failing test or perhaps a small app that exhibits the problem?

**Comment by oza4h07** [comment]
Thank you very much for looking at this !

Did you pick django-netfields master branch on purpose or would you expect the seame result with the 1.2.2 version I used ?

**Comment by higherorderfunctor** [comment]
Is `netfields` added to `INSTALLED_APPS` in the config loaded with `shell_plus`?

**Comment by oza4h07** [comment]
@higherorderfunctor 

`netfields` was missing from `INSTALLED_APPS`
adding it to my `settings.py file, allowed me to have this:
`
>>> LAN.objects.filter(network_address__net_overlaps=net2)
<QuerySet [<LAN: foo>, <LAN: >]>
`
I feel a bit stupid to miss this as it was explicitly mentioned in project's Getting started instructions.

I think this can be marked as SOLVED

And thank you very much for your help

**Comment by higherorderfunctor** [comment]
@oza4h07, good to hear it is working.  Based on the error, it sounded like the lookup function wasn't registering.  It can happen to any of us.

**Comment by oza4h07** [comment]
Thanks again
