### ISSUE TITLE
Add documentation to RTD

### ISSUE THREAD

**Issue by adamcik** [jimfunk/django-postgresql-netfields#11]
Having some proper docs on RTD beyond the minimal info the README covers wouldn't hurt :-)

**Comment by acidjunk** [comment]
+1 for docs

**Comment by adamcik** [comment]
Seeing this project has been doing fine the last ~9 years without this implemented I'm going ahead and closing this issue. If you disagree feel free to reopen.

And on a quick sidenote, thanks again for taking over development and maintainership of this project. It still makes me happy to see new improvements coming in and the project evolving and adding value.
