### ISSUE TITLE
postgresql_psycopg2 deprecation warning (django-netfields 1.2.2)

### ISSUE THREAD

**Issue by i1t** [jimfunk/django-postgresql-netfields#111]
/Users/i1t/.pyenv/versions/3.6.4/lib/python3.6/site-packages/netfields/compat.py:4: RemovedInDjango30Warning: The django.db.backends.postgresql_psycopg2 module is deprecated in favor of django.db.backends.postgresql.
    from django.db.backends.postgresql_psycopg2.base import DatabaseWrapper

**Comment by oza4h07** [comment]
Within this venv, what is the output of 
`python -m pip list | grep netfields`

**Comment by i1t** [comment]
> Within this venv, what is the output of
> `python -m pip list | grep netfields`

`django-netfields           1.2.2`

**Comment by jimfunk** [comment]
What version of Django are you using? It should not be loading that library on Django 3 or grater.

**Comment by i1t** [comment]
> What version of Django are you using? It should not be loading that library on Django 3 or grater.

Django 2.2.6.
