### ISSUE TITLE
Drop support for unmaintained django/python versions

### ISSUE THREAD

**Issue by sevdog** [jimfunk/django-postgresql-netfields#119]
As of now this project still supports django 1.8 (as stated in setup.py) and python 2.7 while at the moment of writing this issue supported django versions are:  3.1, 3.2 and 4.0; and the oldest supported python version is 3.7.

It could make sense to drop support for no more mainteined django and python versions (if there is no particular need to keep them).

By supporting the recent versions the current `compact.py` file and the `six `dependency may be removed.

**Comment by jimfunk** [comment]
I know of at least one app using this today on Django 1.9, and I am OK with maintaining support for a wide variety of versions until it gets actually difficult :-)
