### ISSUE TITLE
Support for psycopg3

### ISSUE THREAD

**Issue by c-w** [jimfunk/django-postgresql-netfields#121]
With the release of Django 4.2, there's now official support for psycopg3 in Django and psycopg2 will eventually be deprecated ([see release notes](https://docs.djangoproject.com/en/4.2/releases/4.2/#psycopg-3-support)).

The use of psycopg2 seems pretty well encapsulated in this library so I wonder if there's a desire to also support the new psycopg3? I can work on a pull request for this if required.

**Comment by jimfunk** [comment]
Yes, psycopg 3.x is probably a good idea. I have been using it in other, non-Django projects.

If you wanted to take a stab at it, go ahead. I should be able to get it going myself, but it probably won't be in the next couple of weeks.

**Comment by c-w** [comment]
Great, thank you. As a conversation starter, I opened a pull request which passes the tests on my machine. Looking forward to your inputs!

**Comment by jimfunk** [comment]
Thanks for the PR.
