### ISSUE TITLE
Can't search on CidrAddressField fields in the admin (Unsupported lookup 'icontains')

### ISSUE THREAD

**Issue by zorun** [jimfunk/django-postgresql-netfields#26]
When trying to search on a CidrAddressField in the admin, it raises an exception:

    FieldError at /admin/resources/ipsubnet/
    Unsupported lookup 'icontains' for CidrAddressField or join on the field not permitted.

`IPSubnet` basically has a `CidrAddressField` and a few other fields:

    class IPSubnet(models.Model):
        inet = CidrAddressField()
        objects = NetManager()

The admin looks like this:

    class IPSubnetAdmin(admin.ModelAdmin):
        search_fields = ('inet__icontains',)
 
The full traceback is here: http://paste.aliens-lyon.fr/Fz4

The same exception happens for many values of search_fields (`inet__contains`, `inet__iexact`, `inet__net_contains`, etc).  However, it works fine when searching just on `inet`, which seems to default to `icontains`.

Note that everything works fine in the Django shell:

    >>> IPSubnet.objects.filter(inet__icontains='100')
    [<IPSubnet: 2a00:5881:4000:100::/56>]
    >>> IPSubnet.objects.filter(inet__iexact='2a00:5881:4000:100:0000:0000:0000:0000/56')
    [<IPSubnet: 2a00:5881:4000:100::/56>]

I'm using Django 1.7 with Python 2.7.

**Comment by rouge8** [comment]
I'm getting a similar error running 0.3:

```pytb
dashboard/libs/views.py:102: in dispatch
    super(CacheableAPIView, self).dispatch(request, *args, **kw)
.tox/py27/lib/python2.7/site-packages/rest_framework/views.py:403: in dispatch
    response = self.handle_exception(exc)
.tox/py27/lib/python2.7/site-packages/rest_framework/views.py:400: in dispatch
    response = handler(request, *args, **kwargs)
dashboard/libs/views.py:141: in get
    return self.list(request, *args, **kwargs)
.tox/py27/lib/python2.7/site-packages/rest_framework/mixins.py:76: in list
    self.object_list = self.filter_queryset(self.get_queryset())
dashboard/apps/organizations/views.py:200: in get_queryset
    return org_assets.filter(ip_address__net_contained=network.cidr)
.tox/py27/lib/python2.7/site-packages/django/db/models/query.py:691: in filter
    return self._filter_or_exclude(False, *args, **kwargs)
.tox/py27/lib/python2.7/site-packages/django/db/models/query.py:709: in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
.tox/py27/lib/python2.7/site-packages/django/db/models/sql/query.py:1331: in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
.tox/py27/lib/python2.7/site-packages/django/db/models/sql/query.py:1358: in _add_q
    current_negated=current_negated, connector=connector)
.tox/py27/lib/python2.7/site-packages/django/db/models/sql/query.py:1230: in build_filter
    condition = self.build_lookup(lookups, col, value)
.tox/py27/lib/python2.7/site-packages/django/db/models/sql/query.py:1149: in build_lookup
    (lookup, lhs.output_field.__class__.__name__))
E   FieldError: Unsupported lookup 'net_contained' for InetAddressField or join on the field not permitted.
```

**Comment by rouge8** [comment]
AHA. Despite what the README says, `netfields` **does** have to be added to `INSTALLED_APPS` on Django 1.7 or newer.
