### ISSUE TITLE
Bug in commit #29

### ISSUE THREAD

**Issue by jmacul2** [jimfunk/django-postgresql-netfields#39]
Previous commit broke __in functionality when passing in a list with one value.  

ie =   Model.objects.filter(netfield__in=['127.0.0.1'])

Since the fix changes the list to a string if it only has one element, it passes the string onto django queryset lookups and breaks.

Can someone tell me why this fix was made in the first place.  I can't figure out what it was trying to fix.

**Comment by jimfunk** [comment]
The in operator here is used in a network sense, eg: '127.0.0.1' is in '127.0.0.0/8'. If you are checking against a single /32 address, would it not make sense to use equality instead?

**Comment by jmacul2** [comment]
I thought that was that __net_contained did?  I am using __in in the traditional sense where I need to select an object that has an ip address that is in a list of addresses.

**Comment by jimfunk** [comment]
Actually, you're right. I will figure something out.
