### ISSUE TITLE
please switch from py2-ipaddress to ipaddress

### ISSUE THREAD

**Issue by cjw296** [jimfunk/django-postgresql-netfields#54]
Many Python distributions now have problems with pip's new strict security requirements and so end up following the steps here:

http://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

Sadly, one of these pulls in this backport as a dependency:

https://pypi.python.org/pypi/ipaddress

Sadly, this is incompatible with the backport you are using:

https://pypi.python.org/pypi/py2-ipaddress

...but both distributions install an ipaddress.py, resulting in heisenbugs when the wrong package ends up being installed last.

I think some changes would be required, but it might make the world a bit of a less crazy place...

**Comment by cjw296** [comment]
When this happens, these are the kinds of exceptions you see:

```
  File ".../lib/python2.7/site-packages/django/db/models/base.py", line 442, in __init__
    setattr(self, field.attname, val)
  File ".../lib/python2.7/site-packages/django/db/models/fields/subclassing.py", line 37, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File ".../lib/python2.7/site-packages/netfields/fields.py", line 95, in to_python
    raise ValidationError(e)
ValidationError: [u"'10.2.0.3' does not appear to be an IPv4 or IPv6 interface"]
```

**Comment by jimfunk** [comment]
I actually had ipaddress in my test virtualenv, but it seems to be fine with Django 1.9, so I never noticed. I just released 0.5.3 which should work with either module.

**Comment by cjw296** [comment]
Thanks for the quick fix :-)

That said, I do hope you get a chance to clean up the weird multiple try/excepts...

**Comment by jimfunk** [comment]
I just updated. Not making a release though until some other changes are made

**Comment by cjw296** [comment]
Awesome, thanks. It may be that @phihag can suggest something better still when he sees the mail to distutils-sig.
