### ISSUE TITLE
Doesn't work with the ArrayField

### ISSUE THREAD

**Issue by scibi** [jimfunk/django-postgresql-netfields#56]
Hi!

I've got a model where I use netfields in array field:

```python
from django.contrib.postgres.fields import ArrayField

class Service(models.Model):
    name = models.CharField(unique=True, max_length=64)
    address_classes = ArrayField(netfields.CidrAddressField(), default=[], 
            blank=True)
```

Unfortunately there is PostgreSQL error when I edit this with admin interface:

```sql
ERROR:  column "address_classes" is of type inet[] but expression is of type text[] at character 177
HINT:  You will need to rewrite or cast the expression.
STATEMENT:  UPDATE "base_service" SET "name" = 'some_name', "address_classes" = ARRAY['10.0.0.0/24', '10.1.0.0/16', '10.2.0.0/20'] WHERE "base_service"."id" = 1
```

I tested it with Django 1.9.4.

**Comment by jimfunk** [comment]
I just got this working, but due to a Django bug that should be fixed in the next version, the types retrieved are strings.

**Comment by scibi** [comment]
Great! Thank you very much :)

**Comment by jmacul2** [comment]
This change seems to break using prefetch_related on models with a MacAddressField as a primary key.

Example:

`Host.objects.filter(mac='00:10:49:00:4f:96').prefetch_related('pools')`

The prefetch related query works, but I believe it cant merge the primary key cause its expecting them to be a macaddr when it uses strings.
