### ISSUE TITLE
Prefixlen lookups should be handled all in one, rather than three separate lookups

### ISSUE THREAD

**Issue by tarkatronic** [jimfunk/django-postgresql-netfields#62]
As brought up in #61:

> This brought to mind a thought: Instead of having 3 lookups: `__prefixlen`, `__max_prefixlen`, and `__min_prefixlen`, wouldn't it make sense to be able to just have a single `__prefixlen` and be able to chain other operations onto it? So for example you could have:
> - `MyModel.objects.filter(network__prefixlen=24)`
> - `MyModel.objects.filter(network__prefixlen__gte=24)`
> - `MyModel.objects.filter(network__prefixlen__lte=24)`
> 
> I don't recall the exact implementation details for something like this, but what are your thoughts?

Currently, using `__gte` or `__lte` produces the following error:

> django.core.exceptions.FieldError: Unsupported lookup 'prefixlen' for CidrAddressField or join on the field not permitted.

**Comment by adamcik** [comment]
I've been out of the loop for Django ORM things for ages, but turning prefixlen into a https://docs.djangoproject.com/en/1.10/ref/models/lookups/#transform-reference looks promising.

**Comment by adamcik** [comment]
https://github.com/jimfunk/django-postgresql-netfields/blob/9837403b328cb6b5c89054ea351c04d11ad8eb8b/netfields/lookups.py#L125 already does this for family, so I think just replacing the Prefixlen lookup with the same setup as for Family would do the trick. Then just keep the `max_prefixlen` / `min_prefixlen` around for backwards compatibility or something :-)

**Comment by tarkatronic** [comment]
Huh, strange. `family` seems an odd one to me to be a transform. But yes, that does look like the trick. Thanks, @adamcik! I'll get on making that change, and probably even put in a `DeprecationWarning` for the `max_prefixlen` and `min_prefixlen`. This will add some "fun" tests!
