### ISSUE TITLE
Gracefully degrade to char fields on non-postgresql

### ISSUE THREAD

**Issue by Elizafox** [jimfunk/django-postgresql-netfields#63]
Gracefully degrading to char fields on non-postgresql database backends would be useful for testing purposes (for instance, I often test on sqlite). postgres-specific operations could be emulated using the ipaddress type.

**Comment by jimfunk** [comment]
We would either have to completely emulate PostgreSQL, which would be very hard to do accurately, not to mention the amount of code that would require, or not perform all of the checks that PostgreSQL would do, which would hide issues when running unit tests.

I just use PostgreSQL for the unit tests in my projects. It's slower, but I don't get any surprises when deploying to production. Newer versions of Django have a --parallel parameter which helps with the speed.
