### ISSUE TITLE
Compatibility issues with Django 2.0a1

### ISSUE THREAD

**Issue by tarkatronic** [jimfunk/django-postgresql-netfields#73]
I've started testing a local application for compatibility with Django 2.0a1, and found that netfields is encountering the following error:

```python
  File ".tox/py36-django20/lib/python3.6/site-packages/netfields/__init__.py", line 1, in <module>
    from netfields.managers import NetManager
  File ".tox/py36-django20/lib/python3.6/site-packages/netfields/managers.py", line 35, in <module>
    class NetQuery(sql.Query):
  File ".tox/py36-django20/lib/python3.6/site-packages/netfields/managers.py", line 36, in NetQuery
    query_terms = sql.Query.query_terms.copy()
AttributeError: type object 'Query' has no attribute 'query_terms'
```

This is with `django-netfields==0.7.2`.

**Comment by tarkatronic** [comment]
As I continue investigating, it appears this is using a long-deprecated piece of code.

The base `NetQuery` class in `managers.py` looks like this:

```python
class NetQuery(sql.Query):
    query_terms = sql.Query.query_terms.copy()
    query_terms.update(NET_OPERATORS)
```

Looking through the history of `django.db.models.sql`, I found the following commits:
https://github.com/django/django/commit/af69f14e7ba06bb7dee257ec02b885f4828c77ff#diff-0edd853580d56db07e4020728d59e193 (Removed unused sql.Query.query_terms) which refers to...
https://github.com/django/django/commit/5008a4db440c8f7d108a6979b959025ffb5789ba (Removed legacy ORM lookup support per deprecation timeline; refs #16187.)

This latter commit exists in every Django version starting with 1.9a1. So it would appear that this has been a long-unsupported variable.

I will continue investigating to see how to work around this.

**Comment by tarkatronic** [comment]
During my digging, I have been able to work through this a little further, but I've run into a bug in django-rest-framework, so until that library has been updated with Django 2.0 compatibility, I believe this will be blocked.

I've opened a ticket here: https://github.com/encode/django-rest-framework/issues/5456

**Comment by orf** [comment]
I've got a MR here: https://github.com/jimfunk/django-postgresql-netfields/pull/74

It's not done just now, but I think I can get it working.

**Comment by jimfunk** [comment]
Apologies for the delay on this.

I just checked in support for Django 2.0. It looks like most of the stuff in managers was unnecessary in Django 1.8+ so removing it seemed to work.

However, the project I'm using this on is stuck at 1.9 due to another dependency. I have a little test app I have for this which is working fine on 2.0b2, but if one of you wanted to try it on your project before I release on pypi, that would be really appreciated.

**Comment by tarkatronic** [comment]
I'll give it a try tomorrow, thanks!

**Comment by washeck** [comment]
With the release of Django 2.0 happening soon can you please release the master as a new version so users can just install it from PyPi?

**Comment by tarkatronic** [comment]
@jimfunk This somehow fell off my radar, but I'm circling back now that Django 2.0 has been released. Running our test suite using the latest master checkout here, it does appear to be working! I'm still running into issues with other packages, but so far this one is no longer standing as a blocker.

**Comment by jimfunk** [comment]
OK, thanks for that. I will have to do a release then. I'm going to need it soon too.
