### ISSUE TITLE
'strict' parameter for network

### ISSUE THREAD

**Issue by virusdefender** [jimfunk/django-postgresql-netfields#83]
By default, some network like `1.2.3.4/24` is not a valid in python `ipaddress` module unless `strict=False` is set.

```
>>> ipaddress.IPv4Network("1.2.3.4/24")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/virusdefender/.pyenv/versions/3.7.0/lib/python3.7/ipaddress.py", line 1536, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 1.2.3.4/24 has host bits set

>>> ipaddress.IPv4Network("1.2.3.4/24", strict=False)
IPv4Network('1.2.3.0/24')
```

However it can be used in pg database.

So there may be some problems due to different validation logic

```
# cidr = InetAddressField(null=True)
>>> SomeModel.objects.filter(cidr__net_overlaps="1.2.3.4/24")
...
...

  File "/Users/virusdefender/Desktop/workspace/waf/venv/lib/python3.7/site-packages/netfields/lookups.py", line 65, in get_prep_lookup
    return str(ipaddress.ip_network(self.rhs))
  File "/Users/virusdefender/.pyenv/versions/3.7.0/lib/python3.7/ipaddress.py", line 74, in ip_network
    return IPv4Network(address, strict)
  File "/Users/virusdefender/.pyenv/versions/3.7.0/lib/python3.7/ipaddress.py", line 1536, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 1.2.3.4/24 has host bits set
```

**Comment by jimfunk** [comment]
There are 2 types in PostgreSQL: INET and CIDR. INET is an individual address which may have a prefix length such as 1.2.3.4/24. CIDR is a network representation, not a host representation, and it may not have bits to the right of the network bits. The types in this module map directly to the PostgreSQL types, which are documented at https://www.postgresql.org/docs/11/datatype-net-types.html.

Mapping to the Python ipaddress module types that are returned, INET maps to ip_interface, while CIDR maps to ip_network. As a special case for the INET field, we made an option to set "store_prefix_length" to False, which always stores the INET field with a prefix length of /32 or /128 depending on the address family, and returns the ip_address type instead.

As for the query you're trying to make, the input is invalid. "net_overlaps" takes a network, not a host address. It is unclear what you're trying to do here, but there are 2 possibilities I can see:

1. Return items where the network contains the given address:

    SomeModel.objects.filter(cidr__net_contains="1.2.3.4/24")

2. Return items where the network overlaps the network for the given address:

    SomeModel.objects.filter(cidr__net_overlaps="1.2.3.0/24")

However, I would recommend always keeping your addresses and networks stored as ipaddress types to keep things clear. For example, if you want to return items in the same network as the address:

    address = ipaddress.ip_interface('1.2.3.4/24')
    SomeModel.objects.filter(cidr__net_overlaps=address.network)

I hope that helps.
