### ISSUE TITLE
Limit fields to a specific family (IPv6, IPv4, or both)

### ISSUE THREAD

**Issue by respawner** [jimfunk/django-postgresql-netfields#88]
It could be a good idea to add a named parameter to fields in order to restrict them to a specific address family.

Of course, I'm not talking about an address family restriction on a database level but on a model level. In this way a model could include only IPv4 (or IPv6) address fields.

By default, a field could accept both IPv6 and IPv4 addresses (or networks) or if given a named parameter (`family` for instance), it will validate the value passed to it, checking it it from the right address family.

I can work on a PR if this issue is proposal is legit.

**Comment by jimfunk** [comment]
That's not actually a function of the database field. This is what validators are for. It's really easy to do, too:

    @deconstructible
    class AddressVersionValidator(BaseValidator):
        compare = lambda self, value, version: value.version != version
        message = 'Must be an IPv%(limit_value)s address.'
        code = 'address_version'

Then you can add the validator to the field definition:

    myaddress = InetAddressField(validators=[AddressVersionValidator(4)])
